#!/bin/sh

cd /scigraph

if [ -z "$1" ]; then
    java -Xmx8g -jar /scigraph/loader.jar -c /scigraph/conf/load-configuration.yaml
else
    java -Xmx8g -jar /scigraph/loader.jar -c "/scigraph/conf/${1}"
fi
